# Generated by Django 2.1.5 on 2019-02-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190201_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iconm',
            new_name='icon',
        ),
    ]
